"""Add CEDEAR instrument, ratio history and ingestion run tables

Revision ID: 0001_cedear_metadata
Revises:
Create Date: 2026-09-29

Written by hand rather than autogenerated so that the exclusion constraint and
its bound semantics are reviewable: half-open periods
``[effective_from, effective_to)`` mean a change effective on day D means day D
already uses the new ratio, and consecutive periods may touch but never
overlap.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_cedear_metadata"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the Phase 2 metadata tables."""
    # Required for the GiST exclusion constraint below: the `=` operator on
    # instrument_id needs btree_gist. The Docker init script already enables
    # it, but a managed instance may not have run that script.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    op.create_table(
        "sg_instruments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("instrument_type", sa.String(length=16), nullable=False),
        sa.Column("underlying_symbol", sa.String(length=64), nullable=True),
        sa.Column("underlying_name", sa.String(length=256), nullable=True),
        sa.Column("underlying_market", sa.String(length=32), nullable=True),
        sa.Column("underlying_market_raw", sa.String(length=64), nullable=True),
        sa.Column("isin", sa.String(length=32), nullable=True),
        sa.Column("underlying_isin", sa.String(length=32), nullable=True),
        sa.Column("custodian", sa.String(length=32), nullable=True),
        sa.Column("program_status", sa.String(length=16), nullable=False),
        sa.Column("program_status_raw", sa.String(length=256), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "first_seen_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "last_seen_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sg_instruments")),
        sa.UniqueConstraint("symbol", name=op.f("uq_sg_instruments_symbol")),
        sa.CheckConstraint(
            "instrument_type IN ('STOCK', 'ETF', 'OTHER', 'UNKNOWN')",
            name=op.f("ck_sg_instruments_instrument_type_known"),
        ),
        sa.CheckConstraint(
            "program_status IN ('ACTIVE', 'INACTIVE', 'UNKNOWN')",
            name=op.f("ck_sg_instruments_program_status_known"),
        ),
    )
    op.create_index(
        "ix_sg_instruments_active_type", "sg_instruments", ["is_active", "instrument_type"]
    )
    op.create_index("ix_sg_instruments_custodian", "sg_instruments", ["custodian"])
    op.create_index("ix_sg_instruments_isin", "sg_instruments", ["isin"])
    op.create_index("ix_sg_instruments_underlying_market", "sg_instruments", ["underlying_market"])
    op.create_index("ix_sg_instruments_underlying_symbol", "sg_instruments", ["underlying_symbol"])

    op.create_table(
        "sg_instrument_ratio_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("ratio", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["sg_instruments.id"],
            name=op.f("fk_sg_instrument_ratio_history_instrument_id_sg_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sg_instrument_ratio_history")),
        sa.CheckConstraint("ratio > 0", name=op.f("ck_sg_instrument_ratio_history_ratio_positive")),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_sg_instrument_ratio_history_effective_range_ordered"),
        ),
        sa.UniqueConstraint(
            "instrument_id",
            "effective_from",
            name="uq_sg_instrument_ratio_history_instrument_id",
        ),
        # A NULL effective_to produces an unbounded daterange, which is how
        # "still in force" is represented.
        postgresql.ExcludeConstraint(
            ("instrument_id", "="),
            (sa.text("daterange(effective_from, effective_to, '[)')"), "&&"),
            using="gist",
            name="ex_sg_instrument_ratio_history_no_overlap",
        ),
    )
    op.create_index(
        "ix_sg_instrument_ratio_history_instrument_from",
        "sg_instrument_ratio_history",
        ["instrument_id", "effective_from"],
    )

    op.create_table(
        "sg_ingestion_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column(
            "sources",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("instruments_seen", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("instruments_created", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("instruments_updated", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("instruments_deactivated", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("ratios_inserted", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "quarantine",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sg_ingestion_runs")),
    )
    op.create_index("ix_sg_ingestion_runs_job", "sg_ingestion_runs", ["job"])


def downgrade() -> None:
    """Drop the Phase 2 metadata tables."""
    op.drop_index("ix_sg_ingestion_runs_job", table_name="sg_ingestion_runs")
    op.drop_table("sg_ingestion_runs")

    op.drop_index(
        "ix_sg_instrument_ratio_history_instrument_from",
        table_name="sg_instrument_ratio_history",
    )
    op.drop_table("sg_instrument_ratio_history")

    for index in (
        "ix_sg_instruments_underlying_symbol",
        "ix_sg_instruments_underlying_market",
        "ix_sg_instruments_isin",
        "ix_sg_instruments_custodian",
        "ix_sg_instruments_active_type",
    ):
        op.drop_index(index, table_name="sg_instruments")
    op.drop_table("sg_instruments")

    # btree_gist may be used by later phases; deliberately left installed.
